apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aiops-assistant.fullname" . }}
  labels: {{ include "aiops-assistant.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aiops-assistant.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aiops-assistant.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "aiops-assistant.fullname" . }}-config
          env: {{ toYaml .Values.env | nindent 12 }}
          ports:
            - containerPort: {{ .Values.config.apiPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.config.apiPort }}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.config.apiPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{ toYaml .Values.resources | nindent 12 }}
